### PR TITLE
validate env variables at runtimes and buildtime

### PR DESCRIPTION
**Pull request by piyushyadav0191**
Being able to validate a env variables on runtime and build time is a very good stuff. It will also be easier for everyone to manage their env variables perfectly as they want!

### CODE REVIEW

**Comment by piyushyadav0191** [comment]
It is similarly to process.env but offers type-safe validation. Therefore, the same data leaks that can occur with process.env can also happen here. While adding extra layers to your data flow can help prevent these issues, it might not be necessary in Josh's new tech

**Comment by klitchevo** [comment]
Thank you for the clarification 👍

**Comment by broisnischal** [comment]
Why to use the t3env when we can create this simply without it!

**Comment by piyushyadav0191** [comment]
It's like you are asking why use Trpc when we can do same with express.

**Comment by joschan21** [comment]
really appreciate the PR, to me this feels like having to know yet another thing to get started though. Would be awesome with a CLI opt-in instead of a standard build-in behavior

**Pull request closed without merging**
